# Generated by Django 5.0.6 on 2024-05-26 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserDeviceMetabolicData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(db_index=True)),
                ('device', models.CharField(max_length=100)),
                ('device_serialnumber', models.CharField(max_length=100)),
                ('device_timestamp', models.DateTimeField()),
                ('recording_type', models.SmallIntegerField()),
                ('glucose_value_history', models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=5, null=True)),
                ('glucose_scan', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('non_numeric_rapid_acting_insulin', models.CharField(blank=True, max_length=255, null=True)),
                ('fast_acting_insulin_units', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('non_numeric_food_data', models.TextField(blank=True, null=True)),
                ('carbohydrates_grams', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('carbohydrates_servings', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('non_numeric_depot_insulin', models.CharField(blank=True, max_length=255, null=True)),
                ('depot_insulin_units', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('glucose_test_strips', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ketone_mmol', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('meal_insulin_units', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('correction_insulin_units', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('insulin_change_by_user_units', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('creation_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
