# Generated by Django 5.0.6 on 2024-05-26 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userdevicemetabolicdata',
            index=models.Index(fields=['glucose_value_history'], name='data_userde_glucose_272368_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevicemetabolicdata',
            index=models.Index(fields=['user_id'], name='data_userde_user_id_9db1ac_idx'),
        ),
    ]
